# these values work with the following helm charts out-of-the-box:
# - https://github.com/kubernetes-csi/csi-driver-smb
# - https://github.com/kubernetes/ingress-nginx/tree/main/charts/ingress-nginx

service:
  type: NodePort

deployment:
  replicas: 1
  image: ghcr.io/kieraneglin/pinchflat:latest
  env:
    TZ: America/New_York

persistence:
  enabled: true
  size: 256Gi
  storageClass: smb
  # for the CSI driver SMB - this chart will create a PVC
  # which will then trigger the driver to create the PV itself
  # after your first install, fill in this field with the created PV name
  #
  # existingVolumeName: pvc-<big-uuid>

db:
  persistence:
    enabled: true
    # TODO: no idea what a good default size should be
    size: 128Gi
    # highly recommend not using a NAS/SMB share here for the time being
    # https://github.com/kieraneglin/pinchflat/wiki/Installation#important-file-permissions
    # I might add in configs to the deployment to tweak things to allow for an
    # easier time, but sqllite dbs running over network storage have not been
    # kind to me in the past so this might take a while
    storageClass: longhorn
    # most CSI drivers will create a pvc here, check to make sure your default
    # one does
    # after your first install, fill in this field with the created PV name
    #
    # existingVolumeName: pvc-<another-big-uuid>

ingress:
  enabled: true
  class: nginx
  host: pinchflat.home.k8s
  tls:
    - hosts:
        - blahblah.org
      secretName: foobar
  annotations:
    nginx.ingress.kubernetes.io/backend-protocol: "HTTP"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "false"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
