{{ $namespace := .Values.namespace }}
{{- if .Values.persistence.enabled }}
{{ with .Values.persistence }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pinchflat-pvc
  namespace: {{ $namespace | default "pinchflat" }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .size }}
  storageClassName: {{ .storageClass }}
  {{- if .existingVolumeName }}
  volumeName: {{ .existingVolumeName }}
  {{- end }}
{{- end }}
{{- end }}
